### ISSUE TITLE
feature: new config format

### ISSUE THREAD

**Issue by scriptnull** [shinobistack/gokakashi#32]
We will need a new config format that is more graph-like.

```yaml
integrations:
  - name: acme-org-docker-hub
    type: docker-hub
    config:
        username: ${DOCKERHUB_USERNAME}
        password: ${DOCKERHUB_PASSWORD}

  - name: acme-project-artifact-registry
    type: google-cloud-artifact-registry
    config:
        auth_type: serviceAccount
        json_key_path: /path/to/sa.json

  - name: acme-linear
    type: linear
    config:
         api_key: ${LINEAR_API_KEY}
         project_id: <>
         team_id: <>
         issue_title: <> 
         issue_priority: <>
         issue_assignee_id: <> 
         issue_state_id: <>
         issue_due_date: <>

site:
    api_token: ${GOKAKASHI_API_TOKEN}
    host: 0.0.0.0
    port: 8000

policies:
    - name: public-service-lts-scans
      image:
          registry: acme-org-docker-hub
          name: acme/public-service
          tags:
              - v2.36.8
              - v2.36.7
      trigger:
          type: cron
          schedule: "0 */8 * * *"
      notify:
         - when:
              severity: [CRITICAL, HIGH]
            to: acme-linear
      labels:
          lts_version: v2.36

  - name: private-service-main-branch-scans
    image:
        pattern: acme/private-service:main-*
    trigger:
        type: ci
     notify:
         - when:
              severity: [CRITICAL, HIGH]
            to: acme-linear
      labels:
          git_branch: main
```

**Comment by scriptnull** [comment]
#### Before

```yaml
policies:
  - name: public-service-lts-scans // Action definition
    image:
      registry: acme-org-docker-hub
      name: acme/public-service
      tags:
        - v2.36.8
        - v2.36.7
    trigger:
      type: cron
      schedule: "0 */8 * * *"
    labels:
      lts_version: v2.36
    check:
      condition: |
         sev.critical > 0 || sev.high > 0 && fixedversion.exist
      notify:
        on_success:
         - acme-linear
         - acme-jira
```

### After

```yaml
policies:
  - name: public-service-lts-scans // Action definition
    image:
      registry: acme-org-docker-hub
      name: acme/public-service
      tags:
        - v2.36.8
        - v2.36.7
    trigger:
      type: cron
      schedule: "0 */8 * * *"
    labels:
      lts_version: v2.36
   notify:
      - to: acme-linear
        when: |
           report.Results.Vulnerabilties.Exists(r, ...)
        format: |
           {{ range .report }}
                {{ ..... }}
            {{ end }}

      - to: acme-jira
        when: |
             .....
```
